honeToType = {
	'Achilles Armor': 'spell',
	'Acid Arrow': 'spell',
	'Acid Fog': 'spell',
	'Acid Spray': 'spell',
	'Add Limb': 'spell',
	'Advancement': 'spell',
	'Alarm': 'spell',
	'Alternate Reality': 'spell',
	'Alter Substance': 'spell',
	'Analyze Item': 'spell',
	'Anchor': 'spell',
	'Animate Item': 'spell',
	'Animate Weapon': 'spell',
	'Anti Plant Shell': 'spell',
	'Arcane Mark': 'spell',
	'Arcane Possession': 'spell',
	'Arms Length': 'spell',
	'a Spell': 'spell',
	'Astral Step': 'spell',
	'Augury': 'spell',
	'Awe': 'spell',
	'Awe Other': 'spell',
	'Big Mouth': 'spell',
	'Blademouth': 'spell',
	'Blind': 'spell',
	'Blink': 'spell',
	'Blur': 'spell',
	'Brainwash': 'spell',
	'Breadcrumbs': 'spell',
	'Burning Hands': 'spell',
	'Cause Stink': 'spell',
	'Chain Lightning': 'spell',
	'Change Sex': 'spell',
	'Channeled Missiles': 'spell',
	'Chant Shield': 'spell',
	'Charm': 'spell',
	'Charm Ward': 'spell',
	'Choke': 'spell',
	'Claireaudience': 'spell',
	'Clairevoyance': 'spell',
	'Clan Donate': 'spell',
	'ClanEnchant Acid': 'spell',
	'ClanEnchant Cold': 'spell',
	'ClanEnchant Disease': 'spell',
	'ClanEnchant Electric': 'spell',
	'ClanEnchant Fire': 'spell',
	'ClanEnchant Gas': 'spell',
	'ClanEnchant Mind': 'spell',
	'ClanEnchant Paralysis': 'spell',
	'ClanEnchant Poison': 'spell',
	'ClanEnchant Water': 'spell',
	'Clan Experience': 'spell',
	'Clan Home': 'spell',
	'Clan Ward': 'spell',
	'Clarify Scroll': 'spell',
	'Clog Mouth': 'spell',
	'Clone': 'spell',
	'Cloudkill': 'spell',
	'Cogniportive': 'spell',
	'Color Spray': 'spell',
	'Combat Precognition': 'spell',
	'Command': 'spell',
	'Comprehend Languages': 'spell',
	'Confusion': 'spell',
	'Conjure Ammunition': 'spell',
	'Conjure Nexus': 'spell',
	'Continual Light': 'spell',
	'Counterspell': 'spell',
	'Darkness': 'spell',
	'Darkness Globe': 'spell',
	'Daydream': 'spell',
	'Deaden Smell': 'spell',
	'Deafen': 'spell',
	'Death Warning': 'spell',
	'Delay': 'spell',
	'Delirium': 'spell',
	'Delude': 'spell',
	'Demon Gate': 'spell',
	'Destroy Object': 'spell',
	'Detect Ambush': 'spell',
	'Detect Gold': 'spell',
	'Detect Hidden': 'spell',
	'Detect Invisible': 'spell',
	'Detect Magic': 'spell',
	'Detect Metal': 'spell',
	'Detect Poison': 'spell',
	'Detect Scrying': 'spell',
	'Detect Sentience': 'spell',
	'Detect Traps': 'spell',
	'Detect Undead': 'spell',
	'Detect Water': 'spell',
	'Detect Weaknesses': 'spell',
	'Disenchant': 'spell',
	'Disenchant Wand': 'spell',
	'Disguise Other': 'spell',
	'Disguise Self': 'spell',
	'Disguise Undead': 'spell',
	'Disintegrate': 'spell',
	'Dismissal': 'spell',
	'Dispel Divination': 'spell',
	'Dispel Magic': 'spell',
	'Distant Vision': 'spell',
	'Divine Beauty': 'spell',
	'Divining Eye': 'spell',
	'Dragonfire': 'spell',
	'Dream': 'spell',
	'Duplicate': 'spell',
	'Earthquake': 'spell',
	'Elemental Storm': 'spell',
	'Enchant Armor': 'spell',
	'Enchant Arrows': 'spell',
	'Enchant Clan Equipment Base Model': 'spell',
	'Enchant Wand': 'spell',
	'Enchant Weapon': 'spell',
	'Endless Hunger': 'spell',
	'Endless Road': 'spell',
	'Enlarge Object': 'spell',
	'Enlightenment': 'spell',
	'Ensnare': 'spell',
	'Enthrall': 'spell',
	'Erase Scroll': 'spell',
	'Exhaustion': 'spell',
	'Fabricate': 'spell',
	'Faerie Fire': 'spell',
	'Faerie Fog': 'spell',
	'Fake Armor': 'spell',
	'Fake Food': 'spell',
	'Fake Spring': 'spell',
	'Fake Weapon': 'spell',
	'Farsight': 'spell',
	'Fatigue': 'spell',
	'Fear': 'spell',
	'Feather Fall': 'spell',
	'Feeblemind': 'spell',
	'Feel The Void': 'spell',
	'Feign Death': 'spell',
	'Feign Invisibility': 'spell',
	'Find Directions': 'spell',
	'Find Familiar': 'spell',
	'Fireball': 'spell',
	'Flagportation': 'spell',
	'Flameshield': 'spell',
	'Flaming Arrows': 'spell',
	'Flaming Ensnarement': 'spell',
	'Flaming Sword': 'spell',
	'Flesh Stone': 'spell',
	'Floating Disc': 'spell',
	'Fly': 'spell',
	'Fools Gold': 'spell',
	'Forceful Hand': 'spell',
	'Forecast Weather': 'spell',
	'Forget': 'spell',
	'Forked Lightning': 'spell',
	'Frailty': 'spell',
	'Free Movement': 'spell',
	'Frenzy': 'spell',
	'Friends': 'spell',
	'Frost': 'spell',
	'Future Death': 'spell',
	'Gate': 'spell',
	'Geas': 'spell',
	'Ghost Sound': 'spell',
	'Giant Strength': 'spell',
	'Globe': 'spell',
	'Grace Of The Cat': 'spell',
	'Gravity Slam': 'spell',
	'Grease': 'spell',
	'Greater Enchant Armor': 'spell',
	'Greater Enchant Weapon': 'spell',
	'Greater Globe': 'spell',
	'Greater Image': 'spell',
	'Greater Invisibility': 'spell',
	'Group Status': 'spell',
	'Grow': 'spell',
	'Gust of Wind': 'spell',
	'Harden Bullets': 'spell',
	'Haste': 'spell',
	'Hear Thoughts': 'spell',
	'Heat Metal': 'spell',
	'Helping Hand': 'spell',
	'Hold': 'spell',
	'Hungerless': 'spell',
	'Ice Lance': 'spell',
	'Ice Sheet': 'spell',
	'Ice Storm': 'spell',
	'Identify Object': 'spell',
	'Ignite': 'spell',
	'Illusory Disease': 'spell',
	'Illusory Wall': 'spell',
	'Immunity': 'spell',
	'Imprisonment': 'spell',
	'Improved Clan Ward': 'spell',
	'Improved Invisibility': 'spell',
	'Improved Planarmorph': 'spell',
	'Improved Polymorph': 'spell',
	'Improved Repairing Aura': 'spell',
	'Increase Gravity': 'spell',
	'Infravision': 'spell',
	'Insatiable Thirst': 'spell',
	'Insect Plague': 'spell',
	'Invisibility': 'spell',
	'Invisibility Sphere': 'spell',
	'Iron Grip': 'spell',
	'Irritation': 'spell',
	'Keen Edge': 'spell',
	'Kinetic Bubble': 'spell',
	'Knock': 'spell',
	'Know Alignment': 'spell',
	'Know Bliss': 'spell',
	'Know Fate': 'spell',
	'Know Origin': 'spell',
	'Know Pain': 'spell',
	'Know Value': 'spell',
	'Laughter': 'spell',
	'Lead Foot': 'spell',
	'Lesser Image': 'spell',
	'Levitate': 'spell',
	'Light': 'spell',
	'Light Blindness': 'spell',
	'Lighten Item': 'spell',
	'Lighthouse': 'spell',
	'Lightning Bolt': 'spell',
	'Light Sensitivity': 'spell',
	'Limb Rack': 'spell',
	'Limited Wish': 'spell',
	'Locate Object': 'spell',
	'Lower Resistance': 'spell',
	'Mage Armor': 'spell',
	'Mage Claws': 'spell',
	'Magical Aura': 'spell',
	'Magic Bullets': 'spell',
	'Magic Item': 'spell',
	'Magic Missile': 'spell',
	'Magic Mouth': 'spell',
	'Major Mana Shield': 'spell',
	'Mana Burn': 'spell',
	'Mana Shield': 'spell',
	'Marker Portal': 'spell',
	'Marker Summoning': 'spell',
	'Mass Disintegrate': 'spell',
	'Mass FeatherFall': 'spell',
	'Mass Fly': 'spell',
	'Mass Haste': 'spell',
	'Mass Hold': 'spell',
	'Mass Invisibility': 'spell',
	'Mass Repairing Aura': 'spell',
	'Mass Sleep': 'spell',
	'Mass Slow': 'spell',
	'Mass Waterbreath': 'spell',
	'Meld': 'spell',
	'Mend': 'spell',
	'Meteor Storm': 'spell',
	'Mind Block': 'spell',
	'Mind Fog': 'spell',
	'Mind Light': 'spell',
	'Minor Image': 'spell',
	'Minor Mana Shield': 'spell',
	'Mirage': 'spell',
	'Mirror Image': 'spell',
	'Misstep': 'spell',
	'Monster Summoning': 'spell',
	'Mute': 'spell',
	'Mystic Loom': 'spell',
	'Mystic Shine': 'spell',
	'Natural Communion': 'spell',
	'Nightmare': 'spell',
	'Obscure Self': 'spell',
	'Pass Door': 'spell',
	'Permanency': 'spell',
	'Phantasm': 'spell',
	'Phantom Hound': 'spell',
	'Planar Banish': 'spell',
	'Planar Block': 'spell',
	'Planar Bubble': 'spell',
	'Planar Burst': 'spell',
	'Planar Extension': 'spell',
	'Planarmorph': 'spell',
	'Planarmorph Self': 'spell',
	'Planar Timer': 'spell',
	'Planeshift': 'spell',
	'Pocket': 'spell',
	'Polymorph': 'spell',
	'Polymorph Object': 'spell',
	'Polymorph Self': 'spell',
	'Portal': 'spell',
	'Portal Other': 'spell',
	'Prayer Shield': 'spell',
	'Prestidigitation': 'spell',
	'Produce Flame': 'spell',
	'Prying Eye': 'spell',
	'Purge Invisibility': 'spell',
	'Read Magic': 'spell',
	'Recharge Wand': 'spell',
	'Refit': 'spell',
	'Reinforce': 'spell',
	'Repairing Aura': 'spell',
	'Repulsion': 'spell',
	'Resist Acid': 'spell',
	'Resist Arrows': 'spell',
	'Resist Bludgeoning': 'spell',
	'Resist Cold': 'spell',
	'Resist Disease': 'spell',
	'Resist Divination': 'spell',
	'Resist Electricity': 'spell',
	'Resist Fire': 'spell',
	'Resist Gas': 'spell',
	'Resist Indignities': 'spell',
	'Resist Magic Missiles': 'spell',
	'Resist Paralysis': 'spell',
	'Resist Petrification': 'spell',
	'Resist Piercing': 'spell',
	'Resist Poison': 'spell',
	'Resist Slashing': 'spell',
	'Returning': 'spell',
	'Reverse Gravity': 'spell',
	'Rogue Limb': 'spell',
	'Scatter': 'spell',
	'Scribe': 'spell',
	'Scry': 'spell',
	'See Aura': 'spell',
	'Shape Object': 'spell',
	'Shatter': 'spell',
	'Shelter': 'spell',
	'Shield': 'spell',
	'Shocking Grasp': 'spell',
	'Shockshield': 'spell',
	'Shoddy Aura': 'spell',
	'Shove': 'spell',
	'Shrink': 'spell',
	'Shrink Mouth': 'spell',
	'Silence': 'spell',
	'Simulacrum': 'spell',
	'Siphon': 'spell',
	'Sleep': 'spell',
	'Slow': 'spell',
	'Slow Projectiles': 'spell',
	'Solve Maze': 'spell',
	'Sonar': 'spell',
	'Song Shield': 'spell',
	'Spellbinding': 'spell',
	'Spell Turning': 'spell',
	'Spider Climb': 'spell',
	'Spook': 'spell',
	'Spotters Orders': 'spell',
	'Spying Stone': 'spell',
	'Stinking Cloud': 'spell',
	'Stone Flesh': 'spell',
	'Stoneskin': 'spell',
	'Summon': 'spell',
	'Summon Army': 'spell',
	'Summon Companion': 'spell',
	'Summon Enemy': 'spell',
	'Summon Flyer': 'spell',
	'Summoning Ward': 'spell',
	'Summon Marker': 'spell',
	'Summon Steed': 'spell',
	'Superior Image': 'spell',
	'Telepathy': 'spell',
	'Teleport': 'spell',
	'Teleportation Ward': 'spell',
	'Teleport Object': 'spell',
	'Thirstless': 'spell',
	'Timeport': 'spell',
	'Time Stop': 'spell',
	'Toadstool': 'spell',
	'Torture': 'spell',
	'Tourettes': 'spell',
	'Transformation': 'spell',
	'True Sight': 'spell',
	'Ugliness': 'spell',
	'Untraceable': 'spell',
	'Ventriloquate': 'spell',
	'Wall of Air': 'spell',
	'Wall of Darkness': 'spell',
	'Wall of Fire': 'spell',
	'Wall of Force': 'spell',
	'Wall of Ice': 'spell',
	'Wall of Stone': 'spell',
	'Ward Area': 'spell',
	'Watchful Hound': 'spell',
	'Water Breathing': 'spell',
	'Water Cannon': 'spell',
	'Weaken': 'spell',
	'Weakness to Acid': 'spell',
	'Weakness to Cold': 'spell',
	'Weakness to Electricity': 'spell',
	'Weakness to Fire': 'spell',
	'Weakness to Gas': 'spell',
	'Web': 'spell',
	'Well Dressed': 'spell',
	'Wish': 'spell',
	'Wizard Lock': 'spell',
	'Wizards Chest': 'spell',
	'Word of Recall': 'spell',
	'Youth': 'spell',
	'Acid Rain': 'chants',
	'Acid Ward': 'chants',
	'Air Wall': 'chants',
	'Airy Aura': 'chants',
	'Alter Time': 'chants',
	'Animal Companion': 'chants',
	'Animal Friendship': 'chants',
	'Animal Growth': 'chants',
	'Animal Spy': 'chants',
	'Ant Train': 'chants',
	'Aquatic Pass': 'chants',
	'Astral Projection': 'chants',
	'Barkskin': 'chants',
	'Bestow Name': 'chants',
	'Bite': 'chants',
	'Blight': 'chants',
	'Bloodhound': 'chants',
	'Bloody Water': 'chants',
	'Blue Moon': 'chants',
	'Boulderbash': 'chants',
	'Brittle': 'chants',
	'Brown Mold': 'chants',
	'Bull Strength': 'chants',
	'Burrowspeak': 'chants',
	'Call Companion': 'chants',
	'Call Mate': 'chants',
	'Calm Animal': 'chants',
	'Calm Seas': 'chants',
	'Calm Weather': 'chants',
	'Calm Wind': 'chants',
	'Camelback': 'chants',
	'Capsize': 'chants',
	'Cats Grace': 'chants',
	'Cave Fishing': 'chants',
	'Cave-In': 'chants',
	'Chant Ward': 'chants',
	'Charge Metal': 'chants',
	'Charm Animal': 'chants',
	'Charm Area': 'chants',
	'Cheetah Burst': 'chants',
	'Chlorophyll': 'chants',
	'Clear Moon': 'chants',
	'Cloud Walk': 'chants',
	'Cold Moon': 'chants',
	'Cold Ward': 'chants',
	'Control Fire': 'chants',
	'Control Plant': 'chants',
	'Control Weather': 'chants',
	'Crossbreed': 'chants',
	'Crystal Growth': 'chants',
	'Darkvision': 'chants',
	'Death Moon': 'chants',
	'Deep Darkness': 'chants',
	'Deep Thoughts': 'chants',
	'Dehydrate': 'chants',
	'Delay Poison': 'chants',
	'Den': 'chants',
	'Distant Fungal Growth': 'chants',
	'Distant Growth': 'chants',
	'Distant Ingrowth': 'chants',
	'Distant Overgrowth': 'chants',
	'Distant Wind Color': 'chants',
	'Dragonsight': 'chants',
	'Drifting': 'chants',
	'Drown': 'chants',
	'Druidic Connection': 'chants',
	'Druidic Pass': 'chants',
	'Eaglesight': 'chants',
	'Earthfeed': 'chants',
	'Earthpocket': 'chants',
	'Eel Shock': 'chants',
	'Eighth Totem': 'chants',
	'Eleventh Totem': 'chants',
	'Enchant Shards': 'chants',
	'Endure Rust': 'chants',
	'Enhance Body': 'chants',
	'Explosive Decompression': 'chants',
	'Favorable Winds': 'chants',
	'Feeding Frenzy': 'chants',
	'Feel Cold': 'chants',
	'Feel Electricity': 'chants',
	'Feel Heat': 'chants',
	'Feel Hunger': 'chants',
	'Feralness': 'chants',
	'Fertile Cavern': 'chants',
	'Fertility': 'chants',
	'Fertilization': 'chants',
	'Fifth Totem': 'chants',
	'Filter Water': 'chants',
	'Find Driftwood': 'chants',
	'Find Gem': 'chants',
	'Find Mate': 'chants',
	'Find Ore': 'chants',
	'Find Plant': 'chants',
	'Fire Ward': 'chants',
	'Fish Gills': 'chants',
	'Flippers': 'chants',
	'Flood': 'chants',
	'Fodder Signal': 'chants',
	'Fortify Food': 'chants',
	'Fourth Totem': 'chants',
	'Free Vine': 'chants',
	'Fungal Bloom': 'chants',
	'Fungus Feet': 'chants',
	'Fur Coat': 'chants',
	'Gas Ward': 'chants',
	'Give Life': 'chants',
	'Golem Form': 'chants',
	'Goodberry': 'chants',
	'Grapevine': 'chants',
	'Grove Walk': 'chants',
	'Grow Club': 'chants',
	'Grow Food': 'chants',
	'Grow Forest': 'chants',
	'Grow Item': 'chants',
	'Grow Oak': 'chants',
	'Harden Skin': 'chants',
	'Hawkeye': 'chants',
	'Healing Moon': 'chants',
	'Hibernation': 'chants',
	'High Tide': 'chants',
	'Hippieness': 'chants',
	'Hold Animal': 'chants',
	'Homeopathy': 'chants',
	'Honey Moon': 'chants',
	'Howlers Moon': 'chants',
	'Illusionary Forest': 'chants',
	'Killer Vine': 'chants',
	# 'Know Plants': 'chants', - scholar
	'Labyrinth': 'chants',
	'Land Legs': 'chants',
	'Land Lungs': 'chants',
	'Life Echoes': 'chants',
	'Lightning Ward': 'chants',
	'Locate Animals': 'chants',
	'Locate Plants': 'chants',
	'Love Moon': 'chants',
	'Magma Cannon': 'chants',
	'Magnetic Earth': 'chants',
	'Magnetic Field': 'chants',
	'Manic Moon': 'chants',
	'Mass Fungal Growth': 'chants',
	'Metal Mold': 'chants',
	'Meteor Strike': 'chants',
	'Mold': 'chants',
	'Moonbeam': 'chants',
	'Moon Calf': 'chants',
	'Move The Sky': 'chants',
	'Muddy Grounds': 'chants',
	'My Plants': 'chants',
	'Natural Balance': 'chants',
	'Natural Order': 'chants',
	'Nectar': 'chants',
	'Neutralize Poison': 'chants',
	'Ninth Totem': 'chants',
	'Pack Call': 'chants',
	'Pale Moon': 'chants',
	'Peace Moon': 'chants',
	'Phosphorescence': 'chants',
	'Piercing Moon': 'chants',
	'Plane Walking': 'chants',
	'Plant Bed': 'chants',
	'Plant Choke': 'chants',
	'Plant Constriction': 'chants',
	'Plant Form': 'chants',
	'Plant Maze': 'chants',
	'Plant Pass': 'chants',
	'Plant Self': 'chants',
	'Plant Snare': 'chants',
	'Plant Trap': 'chants',
	'Plant Wall': 'chants',
	'Poisonous Vine': 'chants',
	'Prayer Ward': 'chants',
	'Predict Phase': 'chants',
	'Predict Tides': 'chants',
	'Predict Weather': 'chants',
	'Purple Moon': 'chants',
	'Quake': 'chants',
	'Reabsorb': 'chants',
	'Read Runes': 'chants',
	'Recharge Shards': 'chants',
	'Recover Voice': 'chants',
	'Red Moon': 'chants',
	'Reef Walking': 'chants',
	'Refresh Runes': 'chants',
	'Reincarnation': 'chants',
	'Rend': 'chants',
	'Repel Vermin': 'chants',
	'Restore Mana': 'chants',
	'Resuscitate Companion': 'chants',
	'Rockfeet': 'chants',
	'Rockthought': 'chants',
	'Root': 'chants',
	'Rust Curse': 'chants',
	'Sacred Earth': 'chants',
	'Sapling Workers': 'chants',
	'Sea Lore': 'chants',
	'Second Totem': 'chants',
	'Sense Age': 'chants',
	'Sense Fluids': 'chants',
	'Sense Gems': 'chants',
	'Sense Metal': 'chants',
	'Sense Ores': 'chants',
	'Sense Plants': 'chants',
	'Sense Poison': 'chants',
	'Sense Pregnancy': 'chants',
	'Sense Sentience': 'chants',
	'Sense Water': 'chants',
	'Seventh Totem': 'chants',
	'Shamblermorph': 'chants',
	'Shapelessness': 'chants',
	'Shape Shift': 'chants',
	'Shillelagh': 'chants',
	'Sift Wrecks': 'chants',
	'Sixth Totem': 'chants',
	'Snatch Light': 'chants',
	'Snuff Flame': 'chants',
	'Soaring Eagle': 'chants',
	'Song Ward': 'chants',
	'Speak With Animals': 'chants',
	'Speed Aging': 'chants',
	'Speed Birth': 'chants',
	'Speed Time': 'chants',
	'Spell Ward': 'chants',
	'Star Gazing': 'chants',
	'Stone Friend': 'chants',
	'Stonewalking': 'chants',
	'Strike Barren': 'chants',
	'Summon Animal': 'chants',
	'Summon Chum': 'chants',
	'Summon Cold': 'chants',
	'Summon Coral': 'chants',
	'Summon Dustdevil': 'chants',
	'Summon Elemental': 'chants',
	'Summon Fear': 'chants',
	'Summon Fire': 'chants',
	'Summon Flower': 'chants',
	'Summon FlyTrap': 'chants',
	'Summon Food': 'chants',
	'Summon Fungus': 'chants',
	'Summon Heat': 'chants',
	'Summon Herbs': 'chants',
	'Summon Houseplant': 'chants',
	'Summon Insects': 'chants',
	'Summon Ivy': 'chants',
	'Summon Jellyfish': 'chants',
	'Summon Moon': 'chants',
	'Summon Mount': 'chants',
	'Summon Peace': 'chants',
	'Summon Plague': 'chants',
	'Summon Plants': 'chants',
	'Summon Pool': 'chants',
	'Summon Rain': 'chants',
	'Summon Rock Golem': 'chants',
	'Summon Sapling': 'chants',
	'Summon School': 'chants',
	'Summon Seaweed': 'chants',
	'Summon Seeds': 'chants',
	'Summon Sun': 'chants',
	'Summon Tree': 'chants',
	'Summon Vine': 'chants',
	'Summon Water': 'chants',
	'Summon Wind': 'chants',
	'Sunbeam': 'chants',
	'Sunray': 'chants',
	'Sweet Scent': 'chants',
	'Tangle': 'chants',
	'Tap Grapevine': 'chants',
	'Tenth Totem': 'chants',
	'Tether': 'chants',
	'Third Totem': 'chants',
	'Thorns': 'chants',
	'Tidal Wave': 'chants',
	'Tide Moon': 'chants',
	'Treeform': 'chants',
	'Treehouse': 'chants',
	'Treemind': 'chants',
	'Treemorph': 'chants',
	'Tremor Sense': 'chants',
	'Tsunami': 'chants',
	'Unbreakable': 'chants',
	'Underwater Action': 'chants',
	'Unicorns Health': 'chants',
	'Uplift': 'chants',
	'Vampire Vine': 'chants',
	'Venomous Bite': 'chants',
	'Venom Ward': 'chants',
	'Vine Mass': 'chants',
	'Vine Weave': 'chants',
	'Volcanic Chasm': 'chants',
	'Waking Moon': 'chants',
	'Warning Winds': 'chants',
	'Warp Wood': 'chants',
	'Water Cover': 'chants',
	'Waterguard': 'chants',
	'Water Hammer': 'chants',
	'Waterspout': 'chants',
	'Water Walking': 'chants',
	'Whirlpool': 'chants',
	'Whisperward': 'chants',
	'White Moon': 'chants',
	'Wind Color': 'chants',
	'Wind Shape': 'chants',
	'Wind Snatcher': 'chants',
	'Worms': 'chants',
	'Yearning': 'chants',
    'Accompaniment': 'songs',
    'Background': 'songs',
    'Ballad': 'songs',
    'Battlehymn': 'songs',
    'Blues': 'songs',
    'Break': 'songs',
    'Carol': 'songs',
    'Clarinets': 'songs',
    'Cymbals': 'songs',
    'Dirge': 'songs',
    'Ditty': 'songs',
    'Drums': 'songs',
    'Flutes': 'songs',
    'Guitars': 'songs',
    'Harmonicas': 'songs',
    'Harmony': 'songs',
    'Harps': 'songs',
    'Horns': 'songs',
    'Love Song': 'songs',
    'Lullabies': 'songs',
    'March': 'songs',
    'Melody': 'songs',
    'Mystical': 'songs',
    'Oboes': 'songs',
    'Organs': 'songs',
    'Pianos': 'songs',
    'Retreat': 'songs',
    'Reveille': 'songs',
    'Rhythm': 'songs',
    'Solo': 'songs',
    'Spiritual': 'songs',
    'Symphony': 'songs',
    'Tempo': 'songs',
    'Tribal': 'songs',
    'Trombones': 'songs',
    'Trumpets': 'songs',
    'Tubas': 'songs',
    'Violins': 'songs',
    'Woods': 'songs',
    'Xylophones': 'songs',
    'Armor': 'songs',
    'Babble': 'songs',
    'Blasting': 'songs',
    'Charm': 'songs',
    'Clumsiness': 'songs',
    'Comprehension': 'songs',
    'Death': 'songs',
    'Detection': 'songs',
    'Dexterity': 'songs',
    'Disgust': 'songs',
    'Distraction': 'songs',
    'Flight': 'songs',
    'Flying': 'songs',
    'Friendship': 'songs',
    'Health': 'songs',
    'Inebriation': 'songs',
    'Knowledge': 'songs',
    'Lethargy': 'songs',
    'Lightness': 'songs',
    'Lullibye': 'songs',
    'Mana': 'songs',
    'Mercy': 'songs',
    'Mute': 'songs',
    'Nothing': 'songs',
    'Ode': 'songs',
    'Pirate Shanty': 'songs',
    'Protection': 'songs',
    'Quickness': 'songs',
    'Rage': 'songs',
    'Rebirth': 'songs',
    'Revelation': 'songs',
    'Saudade': 'songs',
    'Seeing': 'songs',
    'Serenity': 'songs',
    'Silence': 'songs',
    'Single Mindedness': 'songs',
    'Strength': 'songs',
    'Thanks': 'songs',
    'Valor': 'songs',
    'Ballet': 'dances',
    'Basse': 'dances',
    'Butoh': 'dances',
    'Butterfly': 'dances',
    'Can Can': 'dances',
    'Capoeira': 'dances',
    'Clog': 'dances',
    'Cotillon': 'dances',
    'Courante': 'dances',
    'Flamenco': 'dances',
    'Foxtrot': 'dances',
    'Grass': 'dances',
    'Jingledress': 'dances',
    'Jitterbug': 'dances',
    'Macabre': 'dances',
    'Manipuri': 'dances',
    'Morris': 'dances',
    'Musette': 'dances',
    'Polka': 'dances',
    'Rags Sharqi': 'dances',
    'Salsa': 'dances',
    'Square': 'dances',
    'Stop': 'dances',
    'Swing': 'dances',
    'Swords': 'dances',
    'Tango': 'dances',
    'Tap': 'dances',
    'Tarantella': 'dances',
    'Waltz': 'dances',
    'War': 'dances',
    'Absorption': 'prayers',
    'Acid Healing': 'prayers',
    'Adoption': 'prayers',
    'Airy Form': 'prayers',
    'Amplify Unholy Weapon': 'prayers',
    'Anger': 'prayers',
    'Animate Dead': 'prayers',
    'Animate Ghast': 'prayers',
    'Animate Ghost': 'prayers',
    'Animate Ghoul': 'prayers',
    'Animate Mummy': 'prayers',
    'Animate Skeleton': 'prayers',
    'Animate Spectre': 'prayers',
    'Animate Vampire': 'prayers',
    'Animate Zombie': 'prayers',
    'Annul': 'prayers',
    'Anti Undead Field': 'prayers',
    'Atonement': 'prayers',
    'Attune Relic': 'prayers',
    'Attune Scroll': 'prayers',
    'Aura Divine Edict': 'prayers',
    'Aura Fear': 'prayers',
    'Aura Harm': 'prayers',
    'Aura Heal': 'prayers',
    'Aura Intolerance': 'prayers',
    'Avatar': 'prayers',
    'Awaken': 'prayers',
    'Behemoth': 'prayers',
    'Benediction': 'prayers',
    'Benigned Portal': 'prayers',
    'Birds Eye': 'prayers',
    'Blade Barrier': 'prayers',
    'Bless': 'prayers',
    'Blessed Hearth': 'prayers',
    'Bless Item': 'prayers',
    'Blindness': 'prayers',
    'Blindsight': 'prayers',
    'Bloatbomb': 'prayers',
    'Blood Hearth': 'prayers',
    'Blood Moon': 'prayers',
    'Bone Moon': 'prayers',
    'Brightening Aura': 'prayers',
    'Bury': 'prayers',
    'Call Undead': 'prayers',
    'Calm': 'prayers',
    'Cannibalism': 'prayers',
    'Cause Critical': 'prayers',
    'Cause Exhaustion': 'prayers',
    'Cause Fatigue': 'prayers',
    'Cause Light': 'prayers',
    'Cause Serious': 'prayers',
    'Chain Strike': 'prayers',
    'Christen': 'prayers',
    'Cleanliness': 'prayers',
    'Condemnation': 'prayers',
    'Consecrate Land': 'prayers',
    'Contagion': 'prayers',
    'Conviction': 'prayers',
    'Corpse Walk': 'prayers',
    'Corruption': 'prayers',
    'Create Food': 'prayers',
    'Create Idol': 'prayers',
    'Create Water': 'prayers',
    'Cure Blindness': 'prayers',
    'Cure Cannibalism': 'prayers',
    'Cure Critical': 'prayers',
    'Cure Deafness': 'prayers',
    'Cure Disease': 'prayers',
    'Cure Exhaustion': 'prayers',
    'Cure Fatigue': 'prayers',
    'Cure Light': 'prayers',
    'Cure Serious': 'prayers',
    'Cure Vampirism': 'prayers',
    'Curse': 'prayers',
    'Curse Flames': 'prayers',
    'Curse Item': 'prayers',
    'Curse Luck': 'prayers',
    'Curse Metal': 'prayers',
    'Curse Mind': 'prayers',
    'Curse Minds': 'prayers',
    'Daily Bread': 'prayers',
    'Darkening Aura': 'prayers',
    'Dark Senses': 'prayers',
    'Deafness': 'prayers',
    'Deathfinger': 'prayers',
    'Death Guard': 'prayers',
    'Death Knell': 'prayers',
    'Deaths Door': 'prayers',
    'Defile Shield': 'prayers',
    'Deflect Prayer': 'prayers',
    'Demonic Consumption': 'prayers',
    'Demonshield': 'prayers',
    'Deplete Relic': 'prayers',
    'Deplete Scroll': 'prayers',
    'Desecrate': 'prayers',
    'Desecrate Land': 'prayers',
    'Designation': 'prayers',
    'Devourer Curse': 'prayers',
    'Disenchant': 'prayers',
    'Disown': 'prayers',
    'Dispel Evil': 'prayers',
    'Dispel Good': 'prayers',
    'Dispel Undead': 'prayers',
    'Divine Constitution': 'prayers',
    'Divine Guidance': 'prayers',
    'Divine Luck': 'prayers',
    'Divine Perspective': 'prayers',
    'Divine Resistance': 'prayers',
    'Divorce': 'prayers',
    'Doom Aura': 'prayers',
    'Doomspout': 'prayers',
    'Drain': 'prayers',
    'Dream Feast': 'prayers',
    'Drunken Stupor': 'prayers',
    'Earth Mud': 'prayers',
    'Earthshield': 'prayers',
    'Electric Healing': 'prayers',
    'Electric Strike': 'prayers',
    'Elemental Portal': 'prayers',
    'Ember': 'prayers',
    'Empower Holy Armor': 'prayers',
    'Empower Holy Weapon': 'prayers',
    'Empower Relic': 'prayers',
    'Empower Sacred Armor': 'prayers',
    'Empower Sacred Weapon': 'prayers',
    'Empower Scroll': 'prayers',
    'Empower Shield': 'prayers',
    'Empower Unholy Armor': 'prayers',
    'Empower Unholy Weapon': 'prayers',
    'Enchant Relic': 'prayers',
    'Enervate': 'prayers',
    'Eternal Item': 'prayers',
    'Etherealness': 'prayers',
    'Extinguish': 'prayers',
    'Faithful Hellhound': 'prayers',
    'Faithless': 'prayers',
    'Feed The Dead': 'prayers',
    'Feign Life': 'prayers',
    'Fertilize': 'prayers',
    'Fidelity': 'prayers',
    'Find Sacred Item': 'prayers',
    'Fire Healing': 'prayers',
    'Flame Weapon': 'prayers',
    'Flesh Rock': 'prayers',
    'Fluency': 'prayers',
    'Forgive': 'prayers',
    'Fortify Food': 'prayers',
    'Fortress': 'prayers',
    'Fountain Life': 'prayers',
    'Freedom': 'prayers',
    'Freeze Metal': 'prayers',
    'Gateway': 'prayers',
    'Gills': 'prayers',
    'God Light': 'prayers',
    'Godstrike': 'prayers',
    'Great Curse': 'prayers',
    'Greater Warding Glyph': 'prayers',
    'Guardian Hearth': 'prayers',
    'Harm': 'prayers',
    'Haunted': 'prayers',
    'Heal': 'prayers',
    'Heal Mount': 'prayers',
    'Heal Undead': 'prayers',
    'Hellfire': 'prayers',
    'Heresy': 'prayers',
    'Hold Undead': 'prayers',
    'Holy Aura': 'prayers',
    'Holy Day': 'prayers',
    'Holy Shield': 'prayers',
    'Holy Wind': 'prayers',
    'Holy Word': 'prayers',
    'Hunt Evil': 'prayers',
    'Hunt Good': 'prayers',
    'Ice Healing': 'prayers',
    'Illuminate Scroll': 'prayers',
    'Imbue Holy Weapon': 'prayers',
    'Imbue Sacred Weapon': 'prayers',
    'Imbue Shield': 'prayers',
    'Imbue Unholy Weapon': 'prayers',
    'Improved Warding Glyph': 'prayers',
    'Incite Dead': 'prayers',
    'Infuse Balance': 'prayers',
    'Infuse Holiness': 'prayers',
    'Infuse Unholiness': 'prayers',
    'Invigorate': 'prayers',
    'Joyous Rapture': 'prayers',
    'Judgement': 'prayers',
    'Lesser Warding Glyph': 'prayers',
    'Light Hammer': 'prayers',
    'Linked Health': 'prayers',
    'Lower Law': 'prayers',
    'Major Infusion': 'prayers',
    'Maladiction': 'prayers',
    'Maligned Portal': 'prayers',
    'Marry': 'prayers',
    'Mass Blindness': 'prayers',
    'Mass Cure Disease': 'prayers',
    'Mass Deafness': 'prayers',
    'Mass Forgive': 'prayers',
    'Mass Freedom': 'prayers',
    'Mass Grave': 'prayers',
    'Mass Harm': 'prayers',
    'Mass Heal': 'prayers',
    'Mass Mobility': 'prayers',
    'Mass Paralyze': 'prayers',
    'Mass Tongues': 'prayers',
    'Mercy': 'prayers',
    'Minor Infusion': 'prayers',
    'Moderate Infusion': 'prayers',
    'Monolith': 'prayers',
    'Moral Balance': 'prayers',
    'Morph Unholy Weapon': 'prayers',
    'Neutralize Land': 'prayers',
    'Nullification': 'prayers',
    'Omnipresence': 'prayers',
    'Paralyze': 'prayers',
    'Peace Ritual': 'prayers',
    'Philosophy': 'prayers',
    'Piety Curse': 'prayers',
    'Plague': 'prayers',
    'Planar Pilgrimage': 'prayers',
    'Planar Plague': 'prayers',
    'Planar Travel': 'prayers',
    'Poison': 'prayers',
    'Position': 'prayers',
    'Preserve Body': 'prayers',
    'Preserve Knowledge': 'prayers',
    'Prophecy': 'prayers',
    'Prot Bless': 'prayers',
    'Prot Cold': 'prayers',
    'Prot Curses': 'prayers',
    'Prot Death': 'prayers',
    'Prot Disease': 'prayers',
    'Protect Elements': 'prayers',
    'Protect Health': 'prayers',
    'Protect Item': 'prayers',
    'Protect Sacred Item': 'prayers',
    'Prot Evil': 'prayers',
    'Prot Fire': 'prayers',
    'Prot Good': 'prayers',
    'Prot Outsiders': 'prayers',
    'Prot Paralyzation': 'prayers',
    'Prot Poison': 'prayers',
    'Prot Undead': 'prayers',
    'Purify': 'prayers',
    'Read Language': 'prayers',
    'Read Prayer': 'prayers',
    'Recharge Relic': 'prayers',
    'Reflect Prayer': 'prayers',
    'Refuge': 'prayers',
    'Regeneration': 'prayers',
    'Release Prayer': 'prayers',
    'Religious Doubt': 'prayers',
    'Remove Curse': 'prayers',
    'Remove Death Mark': 'prayers',
    'Remove Paralysis': 'prayers',
    'Remove Poison': 'prayers',
    'Restoration': 'prayers',
    'Restore Smell': 'prayers',
    'Restore Voice': 'prayers',
    'Resurrect': 'prayers',
    'Resurrect Mount': 'prayers',
    'Retribution': 'prayers',
    'Revival': 'prayers',
    'Righteous Indignation': 'prayers',
    'Rock Flesh': 'prayers',
    'Rockskin': 'prayers',
    'Rot': 'prayers',
    'Sacred Imbuing Quest': 'prayers',
    'Sacrifice': 'prayers',
    'Sanctify Room': 'prayers',
    'Sanctimonious': 'prayers',
    'Sanctuary': 'prayers',
    'Sanctum': 'prayers',
    'Seekers Prayer': 'prayers',
    'Sense Alignment': 'prayers',
    'Sense Allergies': 'prayers',
    'Sense Chants': 'prayers',
    'Sense Devotion': 'prayers',
    'Sense Disease': 'prayers',
    'Sense Evil': 'prayers',
    'Sense Faithful': 'prayers',
    'Sense Good': 'prayers',
    'Sense Hidden': 'prayers',
    'Sense Injury': 'prayers',
    'Sense Invisible': 'prayers',
    'Sense Life': 'prayers',
    'Sense Magic': 'prayers',
    'Sense Parish': 'prayers',
    'Sense Prayers': 'prayers',
    'Sense Professions': 'prayers',
    'Sense Resistances': 'prayers',
    'Sense Skills': 'prayers',
    'Sense Songs': 'prayers',
    'Sense Spells': 'prayers',
    'Sense Traps': 'prayers',
    'Sense Undead': 'prayers',
    'Sermon': 'prayers',
    'Share Boon': 'prayers',
    'Silence': 'prayers',
    'Snake Staff': 'prayers',
    'Sober': 'prayers',
    'Soul Peering': 'prayers',
    'Speak With Dead': 'prayers',
    'Stasis': 'prayers',
    'Stoning': 'prayers',
    'Store Prayer': 'prayers',
    'Summon Elemental': 'prayers',
    'Sun Curse': 'prayers',
    'Thunderbolt': 'prayers',
    'Tithe': 'prayers',
    'Tongues': 'prayers',
    'Transfer Bane': 'prayers',
    'Transfer Boon': 'prayers',
    'Tremor': 'prayers',
    'True Resurrection': 'prayers',
    'Undead Invisibility': 'prayers',
    'Undeniable Faith': 'prayers',
    'Unholy Armament': 'prayers',
    'Unholy Portent': 'prayers',
    'Unholy Word': 'prayers',
    'Vampirism': 'prayers',
    'Wave': 'prayers',
    'Weather': 'prayers',
    'Wings': 'prayers',
        }

